# Generated by Django 5.0.4 on 2024-05-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='seniority',
            field=models.CharField(choices=[('JR', 'Junior'), ('IN', 'Senior'), ('SR', 'Senior')], default='JR', max_length=2),
        ),
    ]
