# Generated by Django 5.0.4 on 2024-05-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_skill_seniority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='seniority',
            field=models.CharField(choices=[('JR', 'Junior'), ('IN', 'Intermediate'), ('SR', 'Senior ')], default='JR', max_length=2),
        ),
    ]
